all : main

main: main.cpp graph.hpp ../priorityqueue/priority_queue.hpp ../hash_table/hash_table.hpp ../linked_list/linked_list.hpp ../queue/queue.hpp ../linked_stack/linked_stack.hpp
	clear
	g++ -o main main.cpp 
